#!/usr/bin/env python3

import sys
import codecs
from regl.grammar import regl
from regl.model import Document
from regl.lexer import ReglLexer

if __name__ == '__main__':
  if sys.stdout.encoding is None or sys.stdin.encoding is None:
    reload(sys)
    sys.setdefaultencoding('utf-8')
  to_close = []
  if len(sys.argv) > 1:
    if len(sys.argv) > 2:
      fo = codecs.open(sys.argv[2], 'w', 'utf-8')
      to_close.append(fo)
    else:
      fo = sys.stdout
    fi = codecs.open(sys.argv[1], 'r', 'utf-8')
    to_close.append(fi)
  else:
    fi = sys.stdin
  for l in ReglLexer(fi):
    fo.write(l)
  for f in to_close:
    f.close()
